"""empty message

Revision ID: 29ab9ab9f504
Revises: 875879b0cbcc
Create Date: 2020-06-16 20:33:15.642030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ab9ab9f504'
down_revision = '875879b0cbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('login_before', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'login_before')
    # ### end Alembic commands ###
