"""empty message

Revision ID: 557d75335f3a
Revises: f21d5d90d13f
Create Date: 2020-06-06 15:42:27.726045

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from neural_network_runner import DEFAULT_NETWORK

revision = '557d75335f3a'
down_revision = 'f21d5d90d13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    neural_networks_table = op.create_table('neural_networks',
                                            sa.Column('id', sa.Integer(), nullable=False),
                                            sa.Column('code', sa.Text(), nullable=True),
                                            sa.PrimaryKeyConstraint('id')
                                            )
    # ### end Alembic commands ###

    op.bulk_insert(neural_networks_table, [{'id': 1, 'code': DEFAULT_NETWORK}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neural_networks')
    # ### end Alembic commands ###
