"""empty message

Revision ID: 55b56818c446
Revises: 9f5e026c9e0f
Create Date: 2020-05-13 18:45:03.404837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b56818c446'
down_revision = '9f5e026c9e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('first_teammate_name', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('second_teammate_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'second_teammate_name')
    op.drop_column('teams', 'first_teammate_name')
    # ### end Alembic commands ###
