"""empty message

Revision ID: 83bcc1e5feb4
Revises: f6b75c436869
Create Date: 2020-04-28 17:08:13.247454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bcc1e5feb4'
down_revision = 'f6b75c436869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('building_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donations', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_column('donations', 'building_id')
    # ### end Alembic commands ###
