"""empty message

Revision ID: 875879b0cbcc
Revises: 557d75335f3a
Create Date: 2020-06-06 16:33:43.466757

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '875879b0cbcc'
down_revision = '557d75335f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Set all the past campaigns as active
    conn = op.get_bind()
    conn.execute("UPDATE campaigns SET is_active=true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_active')
    # ### end Alembic commands ###
