"""empty message

Revision ID: a92b018b8c85
Revises: 875879b0cbcc
Create Date: 2020-06-18 18:00:12.242034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92b018b8c85'
down_revision = '875879b0cbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('login_before', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'login_before')
    # ### end Alembic commands ###
