"""empty message

Revision ID: b928dfd47ca5
Revises: 4dcd1257e2a0
Create Date: 2020-05-16 18:51:21.317786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b928dfd47ca5'
down_revision = '4dcd1257e2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('first_teammate_name', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('second_teammate_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'second_teammate_name')
    op.drop_column('teams', 'first_teammate_name')
    # ### end Alembic commands ###
