"""empty message

Revision ID: bea6ab68be68
Revises: 4ac0fd4fe0cc
Create Date: 2020-04-15 19:30:03.247730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bea6ab68be68'
down_revision = '4ac0fd4fe0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings_teams',
                    sa.Column('building_id', sa.Integer(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
                    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], )
                    )
    op.add_column('buildings', sa.Column('address', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('center_point', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('buildings', sa.Column('last_campaign_earnings', sa.Float(), nullable=True))
    op.add_column('neighborhoods', sa.Column('center_point', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neighborhoods', 'center_point')
    op.drop_column('buildings', 'last_campaign_earnings')
    op.drop_column('buildings', 'center_point')
    op.drop_column('buildings', 'address')
    op.drop_table('buildings_teams')
    # ### end Alembic commands ###
