"""empty message

Revision ID: d0636517ab6b
Revises: d788d940c324
Create Date: 2020-04-06 22:06:36.584108

"""
from alembic import op
import sqlalchemy as sa
from app_init import bcrypt
from time import localtime, strftime

ADMIN_USER_NAME = "admin"
ADMIN_USER_PASSWORD = bcrypt.generate_password_hash("admin").decode('utf-8')

# revision identifiers, used by Alembic.
revision = 'd0636517ab6b'
down_revision = 'd788d940c324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
                                  sa.Column('id', sa.Integer(), nullable=False),
                                  sa.Column('username', sa.String(length=20), nullable=False),
                                  sa.Column('password', sa.String(), nullable=False),
                                  sa.Column('is_admin', sa.Boolean(), nullable=False),
                                  sa.Column('is_active', sa.Boolean(), nullable=False),
                                  sa.Column('creation_date', sa.DateTime(), nullable=False),
                                  sa.PrimaryKeyConstraint('id'),
                                  sa.UniqueConstraint('username')
                                  )
    # ### end Alembic commands ###
    op.bulk_insert(users_table, [
        {'id': 1, 'username': ADMIN_USER_NAME, 'password': ADMIN_USER_PASSWORD, 'is_admin': True, 'is_active': True,
         'creation_date': strftime("%d-%m-%Y %H:%M:%S", localtime())}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
