"""empty message

Revision ID: f6b75c436869
Revises: f56215d47480
Create Date: 2020-04-21 20:58:50.757503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b75c436869'
down_revision = 'f56215d47480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'transaction_id')
    # ### end Alembic commands ###
