import math

from .consts import DEFAULT_NETWORK

network_code = DEFAULT_NETWORK


def _set_cache(new_code):
    global network_code
    network_code = new_code


def run_network(input):
    """
    Deep learned network model using the tanh activation type.
    Due to the code was auto-generated by a deep learning algorithm it's ugly (but works)
    :param input: of the network
    :return: output of the network
    """
    global network_code

    return eval(network_code)
