STANDARDIZE_TYPE_FLOORS = 'FLOORS'
STANDARDIZE_TYPE_EARNINGS = 'EARNINGS'
STANDARDIZE_TYPE_HEIGHT = 'HEIGHT'
STANDARDIZE_TYPE_NEIGHBORHOOD = 'NEIGHBORHOOD'

STANDARDIZE_INPUTS = {
    STANDARDIZE_TYPE_FLOORS: 100,
    STANDARDIZE_TYPE_EARNINGS: 10000,
    STANDARDIZE_TYPE_HEIGHT: 1000,
    STANDARDIZE_TYPE_NEIGHBORHOOD: 100
}


def encodeInput(input, standardizeType):
    return float(input) / STANDARDIZE_INPUTS[standardizeType]


def decodeInput(input, standardizeType):
    return float(input) * STANDARDIZE_INPUTS[standardizeType]
